### ISSUE TITLE
can't `work-on` with reflex-platform

### ISSUE THREAD

**Issue by sboosali** [ryantrinkle/reflex-todomvc#14]
i ran ` ./work-on ghcjs ./reflex-todomvc` without changing (I think?) either reflex-platform or reflex-todomvc and it errors with:

```
The following packages are broken, either because they have a problem
listed above, or because they depend on a broken package.

haskell-src-meta-0.6.0.14
reflex-0.5.0
reflex-dom-0.4
builder for ‘/nix/store/rgb2ma86k1cms88yp9xwiqlj87cjyylv-ghcjs-0.2.1.drv’ failed with exit code 1

```

i'm under NixOS and cloned reflex-platform yesterday. 

(work-on.log doesn't say anything).

**Comment by Ericson2314** [comment]
I ran `./scripts/work-on ghcjs ./haskell-overlays/reflex-packages/dep/reflex-todomvc` on reflex-platform `master` and it worked just fine. Sorry it wasn't then!
