### ISSUE TITLE
Could not find module ‘GHCJS.DOM.Element’

### ISSUE THREAD

**Issue by k-bx** [ryantrinkle/reflex-todomvc#4]
OS: Mac OS X

Steps to reproduce:
- checkout "try-reflex" to develop branch
- `./try-reflex`
- checkout reflex-todomvc at develop branch
- `cd ../reflex-todomvc`
- `cabal build`

```
[nix-shell:~/workspace/reflex-todomvc]$ cabal build
Building reflex-todomvc-0.1...
Preprocessing library reflex-todomvc-0.1...

src/Reflex/TodoMVC.hs:6:8:
    Could not find module ‘GHCJS.DOM.Element’
    Perhaps you haven't installed the "js_p" libraries for package ‘ghcjs-dom-0.1.1.3@ghcjs_5KR2G57UB1kIpNcQbyzTYs’?
    Use -v to see a list of the files searched for.

src/Reflex/TodoMVC.hs:14:8:
    Could not find module ‘Data.FileEmbed’
    Perhaps you haven't installed the "js_p" libraries for package ‘file-embed-0.0.8.2@filee_01JGu6jgdS04ATSDxnwWLI’?
    Use -v to see a list of the files searched for.

src/Reflex/TodoMVC.hs:18:8:
    Could not find module ‘Reflex’
    Perhaps you haven't installed the "js_p" libraries for package ‘reflex-0.3@refle_2QcAYqBKlbHBt4nVjs8tE5’?
    Use -v to see a list of the files searched for.

src/Reflex/TodoMVC.hs:19:8:
    Could not find module ‘Reflex.Dom’
    Perhaps you haven't installed the "js_p" libraries for package ‘reflex-dom-0.2@refle_0ggRmHHy2NNLe4Bit6HcMy’?
    Use -v to see a list of the files searched for.
```

**Comment by ryantrinkle** [comment]
It looks like you may be building reflex-todomvc with profiling enabled, while the prerequisite libraries were installed without profiling.  Could you try configuring with --disable-library-profiling and --disable-executable-profiling?

**Comment by k-bx** [comment]
@ryantrinkle ah, thanks. That helped! I have library-profiling enabled in global cabal config, but it seems you need to build without profiling when in "./try-reflex"'s env

While this issue is resolved, I wanted to ask one more thing immediately. After a successfull build, I opened `./dist/build/reflex-todomvc/reflex-todomvc.jsexe/index.html` I see error:

```
ReferenceError: h$mainZCMainzimain is not defined
```

Do you have any ideas why that happens?

**Comment by ryantrinkle** [comment]
Good catch!  Looks like that was due to using a re-exported main rather than a main defined in the actual main module.  A fix has been pushed, so if you update try-reflex (or reflex-todomvc), it should work now.

As for profiling, it's not currently supported by try-reflex.  However, it is possible with nix, so we may be able to add it in the future.

**Comment by k-bx** [comment]
No need for profiling, and thanks for the fix!
