### ISSUE TITLE
which is the main branch, on which the development is ongoing?

### ISSUE THREAD

**Issue by emmanueltouzery** [ryantrinkle/reflex-todomvc#8]
i compiled the app from the `ghcjs-improved-base` with the help of the https://github.com/luigy/try-stack-reflex project, and I have a couple of trivial improvements to submit, from `hlint` for now. For instance, using `void` instead of `fmap (const ())` and such. If I keep interest, I may then try to split some of the functions (`todoItem` is a bit of a mouthful at the moment).

but looking at the repo, I'm unsure which the branch to make PRs against actually. `develop` would seem to be the one, but it builds against ghcjs-dom 0.1.*, while `ghcjs-improved-base` build against the 0.2.* newer version?

**Comment by ryantrinkle** [comment]
@emmanueltouzery We use `develop` for ongoing development - `ghcjs-improved-base` is still an experimental branch, which we are testing.  Since reflex-dom's interface will not change much between the two, I don't expect the merge to be too bad.

**Comment by emmanueltouzery** [comment]
hmm ok so if I want to start a small app (hobby, after work) based on reflex now, I should probably base myself on `develop`?  And since you intend to merge both branches, I guess cleanups in either are not productive at this point.. If that's the case I'll hold with them for now.

**Comment by ryantrinkle** [comment]
Yes, unless you need features that are only available with ghcjs-dom-0.2.*, I would recommend sticking with develop.

Cleanups on develop should be fine; when I do the merge from ghcjs-improved-base, I'll make sure to preserve them.

**Comment by emmanueltouzery** [comment]
great, thank you for the answers!
